name: ERC-721 NES - Deploy Version (Patch)

on:
  push:
    tags:
      - deploy-patch

jobs:
  # Need to pull out "tests" into the Github Actions equivalent of CircleCI "orbs"
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx hardhat test
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: cp contracts/ERC721NES.sol ./ERC721NES.sol
    - run: npm version
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - run: |
        git config --global user.name "ERC-721 NES"
        git config --global user.email "no-reply@dev.null"

        git add package.json
        git commit -m "release: update package.json"
        git push